### ISSUE TITLE
Can't install workflow

### ISSUE THREAD

**Issue by Antowkos** [sindresorhus/alfred-xcode#3]
```
npm ERR! Failed at the alfred-xcode@1.1.0 postinstall script 'alfy-init'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alfred-xcode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     alfy-init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alfred-xcode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alfred-xcode
npm ERR! There is likely additional logging output above.
```

Also, it would be nice if I can download `.alfredworkflow` directly.

**Comment by SamVerschueren** [comment]
How do you install the workflow? Which npm version are you using? I have plans on making it very easy to create `.alfredworkflow` packages as a developer.

**Comment by Antowkos** [comment]
Oh! Excuse me for not clarifying this.

I installed npm along with `Node.js v6.11.4` and tried to use this command 
```
npm install --global alfred-xcode
```
There were a lot of errors and warnings, especially about `alfy-init`, so I installed `alfy` too and got only these errors.

**Comment by SamVerschueren** [comment]
What does `npm --version` return?

**Comment by Antowkos** [comment]
`3.10.10`

**Comment by SamVerschueren** [comment]
Can you install something else globally? For instance `npm install -g xo`?  Feel free to remove it again. Just want to find out what the root cause is of this behavior.

**Comment by Antowkos** [comment]
@SamVerschueren yes, this installation was successful.

**Comment by Antowkos** [comment]
Well, I analysed error's output again and find out that it comes from this
```
Error: Command failed: alfred-link
Error: Workflow directory `.../Alfred/Alfred.alfredpreferences/workflows` does not exist
```

I tried to sync my Alfred earlier as described [here](https://www.alfredapp.com/blog/productivity/keep-in-sync-using-dropbox-with-alfred/), but instead of Dropbox I used iCloud and it works not good, so I tried to remove Sync Folder hoping that everything will be fine and it was until now.

The workaround for now is to setup Sync Folder again and after that installation will works like a charm.

**Comment by sindresorhus** [comment]
We done many improvements to the installation process since this. If you still have problems, open an issue on https://github.com/SamVerschueren/alfred-link
