### ISSUE TITLE
Incorrect icon for Xcode files

### ISSUE THREAD

**Issue by bkunat** [sindresorhus/alfred-xcode#5]
After installing this workflow on my new machine, I've noticed that it does not show correct icons for `.xcworkspace` and `.xcodeproj` files:
<img width="62" alt="Screen Shot 2022-01-14 at 13 01 27" src="https://user-images.githubusercontent.com/79861311/149512883-ee861dcf-8ca2-45e9-a32e-202aded957f7.png">

Xcode is set as the default application to open both file types. 

**Notes:**
I've tried re-installing the workflow. 
Everything else works as expected.
I'm currently running on macOS 12.1 (Apple Silicon).

Do you know what might be the issue here?

Also, huge kudos for creating this workflow. It's one of my most frequently used workflows ❤️

**Comment by sindresorhus** [comment]
Seems like something is corrupt with your macOS icon database. This plugin does not actually present the icons.

https://gist.github.com/ismyrnow/e92c6010cda9325b2d8811387a05f224
